### ISSUE TITLE
Hardcoding file locations in ximea.cpp

### ISSUE THREAD

**Issue by stevenwaslander** [wavelab/ximea_camera#2]
This is not great. For anyone.

**Comment by arunxdas** [comment]
Also add functionality to change number of cameras from launch file as part of this issue.  Items to address in this issue:

1) hardcoded paths to camera yaml files
2) hardcoded number of cameras in ximea.cpp
3) update README and add basic usage

**Comment by arunxdas** [comment]
solved in i2 branch, closing issue
